### ISSUE TITLE
Descartar tesoros da errores con índices inválidos.

### ISSUE THREAD

**Issue by mroman42** [mroman42/rbNapakalaki#16]
Debería sólo indicar que el índice es inválido.

**Comment by oxcar103** [comment]
Me he encontrado en la siguiente situación:
Tenía dos objetos de una mano equipados, he perdido contra un monstruo que quita todos los tesoros visibles de manos. Me he descartado de uno y le he dado ha salir. Ha salido!!!

**Comment by oxcar103** [comment]
El problema es que & sólo deja un elemento de cada tipo(aunque esté repetido varias veces en ambas listas). Buscando solución...

**Comment by mroman42** [comment]
Solucionado. Comprueba la validez del índice.
No entiendo el problema de Óscar. Va a una issue aparte.
