### ISSUE TITLE
CardDealer::to_s

### ISSUE THREAD

**Issue by oxcar103** [mroman42/rbNapakalaki#17]
Al mostrar los mazos como: (nº usados / nº sin usar), da la sensación de que estás mostrando: (nº usados / total cartas).
Deberíamos poner algo para quitar esa situación, no?

**Comment by mroman42** [comment]
En el ejemplo que se mostró en clase se hizo así pero si no os gusta se puede poner la suma de usados y sin usar al otro lado. Es un detalle menor.
