### ISSUE TITLE
Mostrar recibo de compra en buyLevels

### ISSUE THREAD

**Issue by mroman42** [mroman42/rbNapakalaki#4]
Quitar el menú de muestra de tesoros y escribir sólo los mínimos diálogos necesarios para que el jugador pueda comprar niveles. Tener en cuenta las reglas del juego.

**Comment by mroman42** [comment]
Ahora mismo está escrito, pero es poco descriptivo para el usuario, que no sabe lo que se está haciendo internamente.

**Comment by mroman42** [comment]
Falta sólo hacer que muestre la suma de monedas y niveles para confirmar la compra.
Debería mostrar al jugador cuántos niveles va a conseguir con la compra.

**Comment by oxcar103** [comment]
Ya está hecha la suma de monedas y niveles. ¿Cierro?
